### ISSUE TITLE
PHP Notice during CSV mass enrolment when no group column is in the CSV file

### ISSUE THREAD

**Issue by danowar2k** [rogiervandongen/moodle-local_mass_enroll#2]
Using the 
PHP Notice:

```
Notice: Undefined offset: 1 in local/mass_enroll/lib.php on line 157
--


1 | 0.0001 | 372848 | {main}( ) | .../mass_enroll.php:0
2 | 0.5400 | 4856312 | local_mass_enroll_renderer->page_mass_enrol( ) | .../mass_enroll.php:55
3 | 0.5937 | 5426816 | mass_enroll( ) | .../renderer.php:80
```

This can be fixed  this way:

```
        if (!isset($fields[1])) $fields[1] = "";
        $group = str_replace('"', '', trim($fields[1]));
```

I've seen you have another commit that fixes this, but since there's no official release of the plugin we used the wrong version (the one in the Moodle plugin directory)...

**Comment by rogiervandongen** [comment]
@danowar2k Thanks for the notification, fix has been made.
Been so busy this year this kind of faded in the background.
Please use the repository version for now (I dont expect to be able to release a proper version on moodle.org this year)
